name: Docker Automation
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: Docker Login, build
        run: |
          echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
          echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME
          }}" --password-stdin
          sudo docker build -t ${{ secrets.DOCKER_USERNAME }}/getting-started:latest .
          sudo docker push ${{ secrets.DOCKER_USERNAME }}/getting-started
    
  deploy:
  
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Docker Setup Compose
        uses: docker/setup-compose-action@v1.2.0
      
      - name: Compose up
        run: |
          docker-compose up -d
          docker ps
