name: TO-DO application docker
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build Docker image
        run: |
          echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
          sudo docker build -t ${{ secrets.DOCKER_USERNAME }}/getting-started:latest .
          sudo docker push ${{ secrets.DOCKER_USERNAME }}/getting-started:latest
    
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Compose up
        run: |
          docker compose up -d
          docker ps
