name: TO-DO application docker
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
               context: .
               push: true
               tags: pranjaldeka/getting-started:1
        
  deploy:
    needs: build
    runs-on: ubuntu-latest 
    steps:
      - name: Compose up
        run: |
          sudo docker compose up -d
          sudo docker ps
